### ISSUE TITLE
Need to run multiple time --fix 

### ISSUE THREAD

**Issue by adelin-b** [ota-meshi/eslint-plugin-yml#273]
when there is keys inside a list inside a list then only the first level is going to be fixe, so we need to run --fix multiple times.

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
However, it is a known limitation.
Since rules report for each key and have a fix for each report, it is necessary to repeat the autofix many times, but ESLint repeats the autofix 10 times with a single lint of the file, and anything that cannot be fixed is reported as is.
A fix to sort the entire file at once might solve the problem, but I won't do that because it might ignore the suppression by the `eslint-disable` comment.

Thank you for understanding.
