### ISSUE TITLE
bug: docs: `flow-sequence-bracket-newline` should only have 1 option

### ISSUE THREAD

**Issue by jimmy-zhening-luo** [ota-meshi/eslint-plugin-yml#340]
# Problem Statement

## Today

The documentation for [`flow-sequence-bracket-newline`](https://ota-meshi.github.io/eslint-plugin-yml/rules/flow-sequence-bracket-newline.html) shows the following [`Options`](https://ota-meshi.github.io/eslint-plugin-yml/rules/flow-sequence-bracket-newline.html#options):

```yaml
yml/flow-sequence-bracket-newline:
  - error
  - always # or "never" or "consistent"
  - multiline: true
    minItems: null
```
> Same as [array-bracket-newline](https://eslint.org/docs/rules/array-bracket-newline) rule option. See [here](https://eslint.org/docs/rules/array-bracket-newline#options) for details.
It also states:

## Issue

- The documentation for `eslint`'s [`array-bracket-newline`](https://eslint.org/docs/latest/rules/array-bracket-newline#options) **contradicts** that of `eslint-plugin-yml`:
- The rule accepts ***one* option, *either* string or object**.

# Proposed Fix

Update [`Options`](https://github.com/ota-meshi/eslint-plugin-yml/blob/master/docs/rules/flow-sequence-bracket-newline.md) to the following:

```yaml
yml/flow-sequence-bracket-newline:
  - error
  - always # or "never" or "consistent"
---
# or
yml/flow-sequence-bracket-newline:
  - error
  - multiline: true
    minItems: null
```

**Comment by ota-meshi** [comment]
Thank you for posting an issue and considering opening a PR!

In OSS, it's best to fork to open a PR. I think this is mostly for security reasons.
This repository uses the `master` branch as the main branch, but if someone malicious creates a `main` branch and pushes a virus, someone else might pull it.

After checking out a fork repository locally, you may find it useful to add a remote for the repository it was forked from, with the name `upstream`.
See also https://eslint.org/docs/latest/contribute/development-environment#step-3-add-the-upstream-source

> Create a new branch issue/341/bug-docs-flow-sequence-bracket-newline-should-only-have-1-option (naming convention?)

Since the fork of the repository is yours, you can name the branches however you like.

> Apply the code fix I propose in the issue descroption
Commit the code fix to my development branch
???

After fixing the issue and pushing to your fork of the repository, if you open the GitHub repository in a browser, you should see a link to make a pull request.

> How do I ensure that the PR I open to fix this issue is actually linked back to the issue? I see that in the GitHub "create PR" interface there's an option to select the issue that the PR is fixing, which again seems a bit flaky to me and is backwards from how every other system I've operated on works (and how I believe it should work): branches are created to fix issues, so they should originate from the issue, both as a matter of UX and as a matter of code-level implementation, where a branch should some how be hash-tied to an issue that spawns it, a more solid notion to me than treating the issue as an arbitrary tag that github.com then knows to display (brittle, non-sensical).

GitHub will automatically link your commit to the issue if you include an issue number in your commit message, or the top comment in a PR thread:

```
fix: Short description of what you did

Longer description here if necessary

Fixes #1234
```

See also https://eslint.org/docs/latest/contribute/pull-requests#step-2-make-your-changes

There are no rules for commit messages or PR titles in this repository. I'm happy to just open a PR.

> How do I unfork?

Sorry, I didn't understand what you meant by "unfork".
Want to delete a fork of your repository? I think you can do that in the settings.

**Comment by jimmy-zhening-luo** [comment]
@ota-meshi thank you! Working on it now.

**Comment by jimmy-zhening-luo** [comment]
It's been a long day so I am exhausted and don't have a lot of words, but I just want to say I am deeply thankful to you for taking the time to patiently teach me above. You shared a lot of knowledge and wisdom with me.

I'll iterate on these PRs as needed until you approve them.

**Comment by jimmy-zhening-luo** [comment]
PR submitted
